[package]
name = "concurrency"
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"

[dependencies]
anyhow = "1.0.91"
crossbeam = "0.8.4"
ntest_timeout = "0.9.3"
rand = "0.8.5"
thiserror = "1.0.65"

