[package]
name = "jq-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
regex = "1.11.0"
serde_json = {version = "1.0", features = ["preserve_order"]}
